# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-08 16:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_memory',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='top_sites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='order',
            name='used_memory',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
