# Generated by Django 2.2 on 2022-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20220713_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='available_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
