# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20220709_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='available_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
