# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_user_other_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ethnicity_hispanic_origin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ethnicity_race',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
