# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20220710_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='other_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
