# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20220710_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(default='hybrid', max_length=50),
            preserve_default=False,
        ),
    ]
